# Site settings
title: "Christos Bacharakis"
email: christos@bacharakis.com
description: "My personal corner on the web"
baseurl: ""
url: "bacharakis.com"
title_description: "Full stack software developer, community manager, public speaker, maker and amateur photographer. I like to find smart solutions for problems with high complexity and blog about them."
title_image: "https://scontent.fath4-1.fna.fbcdn.net/hphotos-ash2/t31.0-8/1799978_10202794286432472_1909537801_o.jpg"
google_analytics: ""
disqus_account:
github_repository: https://github.com/bacharakis/bacharakis.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 7

# Social usernames/URLs
twitter_username: bacharakis
github_username:  bacharakis
linkedin_link: https://gr.linkedin.com/in/christosbaharakis

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
